export const AppState = {
  AUTH: 0,
  TODAYS_PLAN: 1,
  AWAITING_CODE: 2,
  GOAL_SET: 3,
  VERIFYING_PROOF: 4,
  GOAL_COMPLETED: 5,
  EMERGENCY_TEST: 6,
  HISTORY_VIEW: 7,
  AWAITING_BREAK: 8,
  BREAK_ACTIVE: 9,
  BREAK_FAILED: 10,
};
Object.freeze(AppState);
